version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Next.js frontend...
            - docker build -t swiftmarket-ui .
            - docker tag swiftmarket-ui:latest 302263068707.dkr.ecr.eu-north-1.amazonaws.com/swiftmarket-ui:latest
            - docker push 302263068707.dkr.ecr.eu-north-1.amazonaws.com/swiftmarket-ui:latest
artifacts:
    files:
        - '**/*'
